# Generated by Django 4.1.1 on 2022-10-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_group_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=309),
        ),
    ]
